site_name: "CScanner"
site_url: "https://cscanner.io/"
markdown_extensions:
  - admonition
  - meta
  - toc:
      permalink: " "
      separator: "-"
theme:
  name: null
  custom_dir: ./theme/
plugins:
  - macros
nav:
- 'Home': 'index.md'
- 'Compare Editions': 'products/index.md'
- 'Pricing': 'pricing/index.md'
- 'Download': 'download/index.md'
- 'What''s new?': 'updates/index.md'
- 'Docs': 'https://docs.cscanner.io/'
copyright: >
  Copyright &copy; Janos Pasztor
  | <a href="/security/">Security</a>
  | <a href="/terms/">Terms</a>
  | <a href="/imprint/">Imprint</a>
  | <a href="/privacy/">Privacy</a>
extra:
  Y: <span class="yes">Yes</span>
  N: <span class="no">No</span>